AWSTemplateFormatVersion: "2010-09-09"


Description: >
  Create users.  Not regionalized since IAM is global.

Resources:
  BrandonUser:
    Type: "AWS::IAM::User"
    Properties:
      UserName: brandon
  CarlosUser:
    Type: "AWS::IAM::User"
    Properties:
      UserName: carlos
  ElyUser:
    Type: "AWS::IAM::User"
    Properties:
      UserName: ely
